### PR TITLE
Add -bang to skip jumping to first arg

### PR DESCRIPTION
**Pull request by idbrii**
I use Qargs as part of other commands and it annoys me that the first file is opened. This gives me a way to avoid that behavior, but it also complicates what's otherwise a pretty simple plugin.

Maybe this would be better as a new command :QargsNoJump? Then it doesn't need to be a part of Qargs if you don't want to accept it.

:args accepts a bang to drop the current file (like :e!), so that's not
what we want. Instead, we want to clear the arg list (using the
arbitrary high number given by the documentation) and then add our
arguments. If asked to jump to the first, then jump.

I think it makes more sense for the bang to jump to the first arg, but
changing that would break other users.

Also added a modeline.

### CODE REVIEW

**Comment by nelstrom** [comment]
I'm reluctant to let this plugin become more complex. I consider this to be a sort of a 'polyfil' for a workflow that I want to use until Vim provides the necessary commands natively. If this [patch to add `:cdo` and `:ldo` commands](https://groups.google.com/forum/#!topic/vim_dev/dfyt-G6SMec) were included in Vim, it would more or less deprecate `:Qargs` for me.

But maybe you've come up with uses for `:Qargs` that I haven't thought of?

**Comment by idbrii** [comment]
:cdo would cover my use case. I guess I could save and restore the buffer
number instead of preventing buffer changes.

I just wish that argdo, bufdo, and cdo would support that instead of me
having to handle it in anything that uses them.

(I mean like this:
https://github.com/idbrii/vim-searchsavvy/blob/master/autoload/searchsavvy.vim#L106-L119
)

-David

**Comment by nelstrom** [comment]
Ok, we need to lobby for that `:cdo` patch to be accepted!

I've got in to a habit that means I'm not so bothered by `:args` and family changing the active buffer. After running `:Qargs` (or `:args {arglist}`) to populate the argument list, if I want to get back to the buffer I was looking at before I ran the command, I'll press `<C-O>` to go back in the jump-list. Does that help at all?

**Comment by idbrii** [comment]
Is there a good way to put <C-o> into a map?

As far as I can tell you need to use `normal! <C-o><CR>` which can't be followed by other commands?

**Comment by nelstrom** [comment]
I'm really surprised to see that there are no dedicated ex commands for traversing the jumplist. (Even though there is `:jumps` for viewing the jumplist.) I tried your suggestion using `:normal` and it didn't work for me exactly how you've written it. I got it to work by typeing `:normal ` then pressing `ctrl-v` followed by `ctrl-o` then enter. Did you manage to get that single `:normal` command to work as a mapping? If you want to bind more than one `:normal` command to a keymap, you could always wrap them up in a function, then make the keymap call that function.

**Comment by idbrii** [comment]
Sorry, I'm dumb.

I was trying to do something like:

    nnoremap <Leader>fq :Qargs<Bar>normal! <C-o> <Bar>PEditArgs<CR>

Obviously I should just ctrl-o directly:

    nnoremap <Leader>fq :Qargs<CR><C-o>:PEditArgs<CR>

**Comment by idbrii** [comment]
However, that doesn't work for me.

I need to double `<C-o>`

    nnoremap <Leader>fq :Qargs<CR><C-o><C-o>:PEditArgs<CR>

Or I can single `<C-o>` if I change qargs.vim to use keepjumps (#5)

**Comment by idbrii** [comment]
After lots of testing, #5 is sufficient and this PR is unnessary.

**Pull request closed without merging**
